let shopItemsData = [
    {
      id: "item1",
      name: "Casual Shirt",
      price: 500,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
      img: "images/img-1.jpg",
    },
    {
      id: "item2",
      name: "Office Shirt",
      price: 700,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
      img: "images/img-2.jpg",
    },
    {
      id: "item3",
      name: "T-Shirt",
      price: 400,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
      img: "images/img-3.jpg",
    },
    {
      id: "item4",
      name: "Men's Suit",
      price: 1500,
      desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit.",
      img: "images/img-4.jpg",
    },
    {
        id: "item5",
        name: "Mens Tie",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-5.png",
      },
      {
        id: "item6",
        name: "Casual shoes",
        price: 1300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-6.png",
      },
      {
        id: "item7",
        name: "black suit",
        price: 2500,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-7.png",
      },
      {
        id: "item8",
        name: "polo shirt",
        price: 600,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-8.png",
      },
      {
        id: "item9",
        name: "denim shirt",
        price: 1400,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-9.png",
      },
      {
        id: "item10",
        name: "denim pants",
        price: 1800,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-10.png",
      },
      {
        id: "item11",
        name: "basic cap",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-11.png",
      },
      {
        id: "item12",
        name: "leather boots",
        price: 2000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "images/img-12.png",
      },
  ];